[package]
name = "rust_code"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
polars = { version = "0.33", features = ["csv"] }
sysinfo = "0.32.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "minigrep"
path = "src/main.rs"